### ISSUE TITLE
Conversion between incompatible units should raise UnitError, not AttributeError

### ISSUE THREAD

**Issue by markus-beuckelmann** [juhasch/PhysicalQuantities#61]
When trying to convert between incompatible units one would expect `UnitError` to be raised, instead e.g. `PhysicalQuantity(1, 'm').to('kg')` raises `AttributeError("PhysicalUnit instance has no attribute 'unit'")`. This is caused by [line 453](https://github.com/juhasch/PhysicalQuantities/blob/a44cc27126dca7cf539559587561158182f89224/PhysicalQuantities/Unit.py#L453)  in Unit.py, introduced by b1f54a154e97acee4d77751d66e8b6e8d545c295.

```
>>> PhysicalQuantity(1, 'm').to('kg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/PhysicalQuantities/Quantity.py", line 565, in to
    value = convertvalue(self.value, self.unit, unit)
  File "/usr/lib/python2.7/site-packages/PhysicalQuantities/Unit.py", line 58, in convertvalue
    (factor, offset) = src_unit.conversion_tuple_to(target_unit)
  File "/usr/lib/python2.7/site-packages/PhysicalQuantities/Unit.py", line 453, in conversion_tuple_to
    raise UnitError('Incompatible unit for conversion %s' % other.unit)
AttributeError: PhysicalUnit instance has no attribute 'unit'
```

@juhasch, how about just going back to `raise UnitError('Incompatible units')` as in e10ab547de71f774ae91e441ff2ece9b634afccc?

**Comment by juhasch** [comment]
Yes, this is a bug. Should have been caught by a test...
Fixed by #62.
